import { randomUUID } from "node:crypto"

export type IdPrefix =
  | "user"
  | "proj"
  | "pws"
  | "pres"
  | "pins"
  | "conv"
  | "sess"
  | "turn"
  | "trc"
  | "msg"
  | "evt"
  | "mcall"
  | "chunk"
  | "usage"
  | "ctxuse"
  | "tcall"
  | "appr"
  | "sh"
  | "shout"
  | "fop"
  | "patch"
  | "err"
  | "art"
  | "voicein"
  | "audioout"
  | "fb"
  | "conn"

export const createId = (prefix: IdPrefix): string => `${prefix}_${randomUUID().replaceAll("-", "")}`
