import type { MemoryAgentJournalOutput, MemoryAgentSummarySections } from "@socrates/contracts"
import { memoryAgentJournalOutputSchema } from "@socrates/contracts"
import { createId } from "@socrates/shared"

export type MemoryJournalRowLike = {
  id: string
  jobId: string
  summary: string
  patternsObservedJson: string
  skillsAffectedJson: string
  decisionsJson: string
  openInvestigationsJson: string
  nextRunFocusJson: string
  providerId: string
  modelId: string
  thinkingEnabled: boolean
  thinkingEffort: string | null
  status: string
  createdAt: string
  metadataJson: string | null
}

export const normalizeMemoryJournalOutput = (
  output: MemoryAgentJournalOutput,
  previous?: MemoryAgentJournalOutput,
): MemoryAgentJournalOutput => {
  const previousByTitle = new Map(
    (previous?.openInvestigations ?? []).map((item) => [normalizeTitle(item.title), item.investigationId]),
  )
  return {
    ...output,
    openInvestigations: output.openInvestigations.map((item) => ({
      ...item,
      investigationId: item.investigationId ?? previousByTitle.get(normalizeTitle(item.title)) ?? createId("meminv"),
    })),
  }
}

export const journalOutputFromRow = (row: MemoryJournalRowLike): MemoryAgentJournalOutput =>
  memoryAgentJournalOutputSchema.parse({
    summary: row.summary,
    patternsObserved: parseArray(row.patternsObservedJson),
    skillsAffected: parseArray(row.skillsAffectedJson),
    decisions: parseArray(row.decisionsJson),
    openInvestigations: parseArray(row.openInvestigationsJson),
    nextRunFocus: parseArray(row.nextRunFocusJson),
  })

export const journalOutputToDisplaySummary = (output: MemoryAgentJournalOutput): MemoryAgentSummarySections => ({
  investigated: [
    output.summary,
    ...output.patternsObserved.map((pattern) => `- ${pattern.name}: ${pattern.finding}`),
  ].join("\n"),
  changed: output.skillsAffected.length > 0
    ? output.skillsAffected.map((skill) => `- ${skill.action}${skill.skillId ? ` (${skill.skillId})` : ""}: ${skill.note}`).join("\n")
    : "",
  skipped: output.decisions.length > 0 ? output.decisions.map((decision) => `- ${decision}`).join("\n") : "",
  blocked: output.openInvestigations.length > 0
    ? output.openInvestigations.map((item) => `- ${item.title}: ${item.currentUnderstanding} Next: ${item.nextStep}`).join("\n")
    : "",
})

export const renderMemoryAgentLedger = (input: {
  generatedAt: string
  totalRuns: number
  totalSkillProposals: number
  completedSkillWriterJobs: number
  createdSkills: number
  updatedSkills: number
  recentSkillOutcomes: string[]
  latestRuns: Array<{ row: MemoryJournalRowLike; output: MemoryAgentJournalOutput }>
}): string => {
  const latest = input.latestRuns[0]?.output
  const lines = [
    "---",
    "generated: true",
    `generated_at: ${input.generatedAt}`,
    "source_of_truth: memory_agent_journal",
    "---",
    "",
    "# Memory Agent Ledger",
    "",
    "> Runtime-generated briefing snapshot. Do not edit this file; the database journal is authoritative.",
    "",
    "## Automatic Stats",
    "",
    `- Completed journal runs: ${input.totalRuns}`,
    `- Skill proposals recorded: ${input.totalSkillProposals}`,
    `- Skill Writer jobs completed: ${input.completedSkillWriterJobs}`,
    `- Skills created by Skill Writer: ${input.createdSkills}`,
    `- Skills updated by Skill Writer: ${input.updatedSkills}`,
    "",
    "## Recent Skill Outcomes",
    "",
    ...(input.recentSkillOutcomes.length ? input.recentSkillOutcomes.map((item) => `- ${item}`) : ["None."]),
    "",
    "## Current Handoff",
    "",
    latest?.summary ?? "No completed Memory Agent journal run yet.",
    "",
    "## Open Investigations",
    "",
    ...(latest?.openInvestigations.length
      ? latest.openInvestigations.map((item) => `- ${item.investigationId}: **${item.title}** — ${item.currentUnderstanding} Next: ${item.nextStep}`)
      : ["None."]),
    "",
    "## Next Run Focus",
    "",
    ...(latest?.nextRunFocus.length ? latest.nextRunFocus.map((item) => `- ${item}`) : ["None."]),
    "",
    "## Recent Run Summaries",
    "",
    ...(input.latestRuns.length
      ? input.latestRuns.map(({ row, output }) => `- ${row.createdAt} | ${row.jobId} | ${output.summary}`)
      : ["None."]),
    "",
  ]
  return `${lines.join("\n")}\n`
}

const normalizeTitle = (value: string): string => value.trim().toLowerCase().replace(/\s+/g, " ")

const parseArray = (value: string): unknown[] => {
  try {
    const parsed = JSON.parse(value)
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}
