import { createHash } from "node:crypto"
import fs from "node:fs"
import path from "node:path"
import {
  memoryDocFrontmatterSchema,
  memoryDocRequiredSections,
  memoryDocTypeSchema,
  type MemoryDocIndex,
  type MemoryDocFrontmatter,
  type MemoryDocOwnerTool,
  type MemoryDocScope,
  type MemoryDocSection,
  type MemoryDocType,
} from "@socrates/contracts"
import { SocratesError } from "@socrates/shared"

export type MemoryDocProfile = {
  docType: MemoryDocType
  ownerTool: MemoryDocOwnerTool
  scope: MemoryDocScope
  path: string
  projectId?: string
  indexTags?: string[]
}

type SectionDefinition = {
  id: string
  kind: string
  heading: string
  tags?: string[]
  body?: string
}

const STATE_LEDGER_START = "<!-- socrates-state-ledger:start -->"
const STATE_LEDGER_END = "<!-- socrates-state-ledger:end -->"

const sectionDefinitions: Record<MemoryDocType, SectionDefinition[]> = {
  project_memory: [
    { id: "current_state", kind: "state", heading: "Current State", tags: ["handoff", "status"], body: "- Current project standing belongs here." },
    { id: "durable_decisions", kind: "decisions", heading: "Durable Decisions", tags: ["architecture"], body: "- Stable decisions that should survive across chats belong here." },
    { id: "constraints", kind: "constraints", heading: "Constraints", tags: ["rules"], body: "- Durable project constraints belong here." },
    { id: "project_preferences", kind: "preferences", heading: "Project Preferences", tags: ["user"], body: "- Project-specific user preferences belong here." },
    { id: "blockers", kind: "blockers", heading: "Blockers", tags: ["handoff"], body: "- Long-lived blockers belong here." },
    { id: "handoff", kind: "handoff", heading: "Handoff", tags: ["restart"], body: "- Restart-ready handoff facts belong here." },
    { id: "evidence_anchors", kind: "anchors", heading: "Evidence Anchors", tags: ["source"], body: "- Exact evidence pointers belong here." },
  ],
  project_notes: [
    {
      id: "runtime_context",
      kind: "system",
      heading: "Runtime Context",
      tags: ["runtime", "generated", "system"],
      body: [
        "system_owned: true",
        "generated_at: never",
        "signature: none",
        "workspace:",
        "  root: unknown",
        "python:",
        "  virtual_environments:",
        "    - none",
        "  dependency_files:",
        "    - none",
        "  package_managers:",
        "    - none",
        "terminal_state: omitted",
        "notes:",
        "  - Runtime workspace scan facts are generated by the backend.",
        "  - Terminal output and live terminal state are intentionally not persisted here.",
      ].join("\n"),
    },
    {
      id: "state_ledger",
      kind: "state",
      heading: "State Ledger",
      tags: ["machine", "startup"],
      body: [
        STATE_LEDGER_START,
        "## Socrates State Ledger",
        "",
        "Machine-managed compact state for startup context. Preserve this bounded section; human notes can live outside it.",
        "",
        "- Updated: never",
        "- Last turn: none",
        "- Recent tools: none",
        "- Files touched: none",
        "- Commands: none",
        "- Startup hint: read full project notes with project_docs({operation:\"read\", area:\"notes\"}) when more detail is needed.",
        STATE_LEDGER_END,
      ].join("\n"),
    },
    { id: "active_todos", kind: "todos", heading: "Active Todos", tags: ["work"], body: "- Active todos belong here." },
    { id: "checked_files", kind: "files", heading: "Checked Files", tags: ["work"], body: "- Files already checked belong here." },
    { id: "next_commands", kind: "commands", heading: "Next Commands", tags: ["work"], body: "- Next useful commands belong here." },
    { id: "scratch_notes", kind: "scratch", heading: "Scratch Notes", tags: ["temporary"], body: "- Temporary investigation notes belong here." },
    { id: "completed_archive", kind: "archive", heading: "Completed Archive", tags: ["history"], body: "- Completed short-term notes can be condensed here." },
  ],
  repo_core_idea: [
    { id: "purpose", kind: "purpose", heading: "Purpose", tags: ["overview"], body: "- What this workspace is for:" },
    { id: "current_direction", kind: "state", heading: "Current Direction", tags: ["status"], body: "- Current priority:" },
    { id: "milestones", kind: "milestones", heading: "Milestones", tags: ["planning"], body: "- Next durable milestone:" },
    { id: "update_triggers", kind: "rules", heading: "Update Triggers", tags: ["maintenance"], body: "- Update when purpose, phase, or direction changes." },
  ],
  repo_navigation: [
    { id: "ownership_map", kind: "navigation", heading: "Ownership Map", tags: ["files"], body: "- Important folders:" },
    { id: "entry_points", kind: "navigation", heading: "Entry Points", tags: ["files"], body: "- Entry points:" },
    { id: "tests", kind: "testing", heading: "Tests", tags: ["verification"], body: "- Test locations:" },
    { id: "generated_ignored", kind: "navigation", heading: "Generated And Ignored Areas", tags: ["files"], body: "- Generated or ignored output:" },
    { id: "navigation_rules", kind: "rules", heading: "Navigation Rules", tags: ["workflow"], body: "- Where to look first:" },
  ],
  repo_rules: [
    { id: "hard_rules", kind: "rules", heading: "Hard Rules", tags: ["constraints"], body: "- Preserve user work; do not revert unrelated changes." },
    { id: "workflows", kind: "workflow", heading: "Workflows", tags: ["process"], body: "- Preferred workflows belong here." },
    { id: "verification", kind: "verification", heading: "Verification", tags: ["tests"], body: "- Verify meaningful changes with the narrowest reliable check." },
    { id: "known_pitfalls", kind: "pitfalls", heading: "Known Pitfalls", tags: ["risk"], body: "- Recurring mistakes belong here." },
    { id: "update_triggers", kind: "rules", heading: "Update Triggers", tags: ["maintenance"], body: "- Update when stable repo conventions or verification workflows change." },
  ],
  repo_contracts: [
    { id: "tool_contracts", kind: "contracts", heading: "Tool Contracts", tags: ["tools"], body: "- Tool input/output contracts:" },
    { id: "api_contracts", kind: "contracts", heading: "API Contracts", tags: ["api"], body: "- API routes:" },
    { id: "db_event_contracts", kind: "contracts", heading: "Database And Event Contracts", tags: ["db", "events"], body: "- Persistence invariants:" },
    { id: "frontend_backend", kind: "contracts", heading: "Frontend Backend Responsibilities", tags: ["frontend", "backend"], body: "- UI/runtime expectations:" },
    { id: "change_log", kind: "changes", heading: "Change Log", tags: ["maintenance"], body: "- Contract changes belong here." },
  ],
  identity: [
    {
      id: "identity",
      kind: "identity",
      heading: "Identity",
      tags: ["soul"],
      body: [
        "- Socrates is a local-first project partner.",
        "- Socrates works from evidence in the current workspace, repo docs, tool traces, and explicit user instructions.",
        "- Durable user profile and stable cross-project preferences live in `user_profile.md` and are accessed through the `user_profile` tool.",
      ].join("\n"),
    },
    { id: "scope", kind: "scope", heading: "Scope", tags: ["soul"], body: "- Runtime, developer, and user instructions outrank this file." },
    { id: "non_negotiables", kind: "rules", heading: "Non-Negotiables", tags: ["soul"], body: "- Do not store secrets, credentials, private keys, or sensitive raw data." },
    { id: "voice", kind: "style", heading: "Voice", tags: ["soul"], body: "- Be direct, concrete, and technically grounded." },
    { id: "change_policy", kind: "rules", heading: "Change Policy", tags: ["soul"], body: "- Update only from explicit user statements or repeated behavior with clear support in traces." },
  ],
  operating_principles: [
    { id: "decision_principles", kind: "principles", heading: "Decision Principles", tags: ["behavior"], body: "- Prefer evidence over assumption.\n- Use trace retrieval when prior conversation or tool evidence matters." },
    { id: "tool_discipline", kind: "tools", heading: "Tool Discipline", tags: ["behavior"], body: "- Read/search before editing." },
    { id: "memory_discipline", kind: "memory", heading: "Memory Discipline", tags: ["behavior"], body: "- Keep project memory concise and inspectable.\n- Store global principles only when they are durable across projects.\n- Keep project-specific state inside the workspace `.socrates/` tree." },
    { id: "safety", kind: "safety", heading: "Safety", tags: ["behavior"], body: "- Stop and ask before destructive or sensitive actions without explicit instruction." },
    { id: "failure_handling", kind: "recovery", heading: "Failure Handling", tags: ["behavior"], body: "- Report failing commands and continue debugging unless the user asked only for diagnosis." },
  ],
  user_profile: [
    { id: "stable_facts", kind: "profile", heading: "Stable Facts", tags: ["user"], body: "Root global user profile for Socrates. Runtime, developer, and user instructions outrank this file.\n\n- Unknown until repeated or explicit evidence justifies a durable note." },
    { id: "stable_preferences", kind: "preferences", heading: "Stable Preferences", tags: ["user"], body: "- Durable cross-project preferences belong here." },
    { id: "collaboration_style", kind: "style", heading: "Collaboration Style", tags: ["user"], body: "- Prefer direct, concrete, technically grounded communication." },
    { id: "boundaries", kind: "boundaries", heading: "Boundaries", tags: ["user"], body: "- Do not store secrets, credentials, private keys, or sensitive raw data." },
    { id: "evidence_requirements", kind: "evidence", heading: "Evidence Requirements", tags: ["user"], body: "- Update only from explicit statements or repeated behavior with clear support in traces." },
    { id: "stale_or_rejected_facts", kind: "stale", heading: "Stale Or Rejected Facts", tags: ["user"], body: "- Superseded or rejected profile facts belong here." },
  ],
  tool_doc: [
    { id: "purpose", kind: "purpose", heading: "Purpose", tags: ["tools"], body: "- What this tool guidance is for." },
    { id: "when_to_use", kind: "routing", heading: "When To Use", tags: ["tools"], body: "- When to call this tool." },
    { id: "inputs", kind: "schema", heading: "Inputs", tags: ["tools"], body: "- Important inputs and constraints." },
    { id: "correct_flow", kind: "workflow", heading: "Correct Flow", tags: ["tools"], body: "- Preferred tool flow." },
    { id: "failure_handling", kind: "recovery", heading: "Failure Handling", tags: ["tools"], body: "- How to recover from common failures." },
    { id: "examples", kind: "examples", heading: "Examples", tags: ["tools"], body: "- Examples belong here." },
    { id: "update_policy", kind: "rules", heading: "Update Policy", tags: ["tools"], body: "- Update when stable tool behavior or recurring misuse changes." },
  ],
  skill: [
    { id: "purpose", kind: "purpose", heading: "Purpose", tags: ["skills"], body: "- What this skill is for." },
    { id: "workflow", kind: "workflow", heading: "Workflow", tags: ["skills"], body: "- Steps to follow." },
    { id: "examples", kind: "examples", heading: "Examples", tags: ["skills"], body: "- Examples belong here." },
    { id: "update_policy", kind: "rules", heading: "Update Policy", tags: ["skills"], body: "- Update when the reusable workflow changes." },
  ],
}

export const parseMemoryDoc = (content: string, profile: MemoryDocProfile): MemoryDocIndex => {
  const parsedFrontmatter = parseFrontmatter(content)
  const warnings: string[] = []
  let body = content
  let frontmatter: MemoryDocFrontmatter = {
    socrates_doc: profile.docType,
    schema_version: 1,
    owner_tool: profile.ownerTool,
    scope: profile.scope,
  }
  if (profile.indexTags && profile.indexTags.length > 0) {
    frontmatter = { ...frontmatter, index_tags: profile.indexTags }
  }
  let bodyLineOffset = 0
  if (parsedFrontmatter) {
    body = parsedFrontmatter.body
    bodyLineOffset = parsedFrontmatter.bodyLineOffset
    const validated = memoryDocFrontmatterSchema.safeParse(parsedFrontmatter.data)
    if (validated.success) {
      frontmatter = validated.data
      if (frontmatter.socrates_doc !== profile.docType) {
        warnings.push(`Frontmatter doc type ${frontmatter.socrates_doc} did not match expected ${profile.docType}.`)
      }
      if (frontmatter.owner_tool !== profile.ownerTool) {
        warnings.push(`Frontmatter owner ${frontmatter.owner_tool} did not match expected ${profile.ownerTool}.`)
      }
      if (frontmatter.scope !== profile.scope) {
        warnings.push(`Frontmatter scope ${frontmatter.scope} did not match expected ${profile.scope}.`)
      }
    } else {
      warnings.push("Frontmatter was present but did not match the Socrates memory-doc schema.")
    }
  } else {
    warnings.push("Document has no Socrates memory-doc frontmatter.")
  }

  const sections = parseSections(body, bodyLineOffset)
  const required = memoryDocRequiredSections[profile.docType]
  const existing = new Set(sections.map((section) => section.sectionId))
  for (const requiredSection of required) {
    if (!existing.has(requiredSection)) {
      warnings.push(`Missing required section ${requiredSection}.`)
    }
  }

  return {
    path: profile.path,
    scope: profile.scope,
    ...(profile.projectId ? { projectId: profile.projectId } : {}),
    docType: profile.docType,
    ownerTool: profile.ownerTool,
    schemaVersion: frontmatter.schema_version,
    contentHash: hashText(content),
    sections,
    ...(warnings.length > 0 ? { warnings } : {}),
  }
}

export const ensureStructuredMemoryDoc = (filePath: string, profile: MemoryDocProfile): void => {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, buildStructuredMemoryDoc(profile))
    return
  }
  const current = fs.readFileSync(filePath, "utf8")
  try {
    const parsed = parseMemoryDoc(current, profile)
    if (isValidStructuredMemoryDoc(parsed, profile.docType)) {
      return
    }
  } catch {
    // Preserve the original text in a legacy section instead of failing startup on a malformed doc.
  }
  fs.writeFileSync(filePath, buildStructuredMemoryDoc(profile, { legacyContent: current }))
}

export const buildStructuredMemoryDoc = (profile: MemoryDocProfile, options: { legacyContent?: string } = {}): string => {
  const title = titleForProfile(profile)
  const frontmatter = [
    "---",
    `socrates_doc: ${profile.docType}`,
    "schema_version: 1",
    `owner_tool: ${profile.ownerTool}`,
    `scope: ${profile.scope}`,
    profile.indexTags && profile.indexTags.length > 0 ? `index_tags: [${profile.indexTags.join(", ")}]` : undefined,
    "---",
    "",
  ].filter((line): line is string => typeof line === "string")
  const sections = sectionDefinitions[profile.docType].map(renderSection)
  const legacy = options.legacyContent?.trim()
  if (legacy) {
    sections.push(
      renderSection({
        id: "legacy_content",
        kind: "legacy",
        heading: "Legacy Content",
        tags: ["migration"],
        body: legacy,
      }),
    )
  }
  return [...frontmatter, `# ${title}`, "", ...sections].join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n"
}

export const patchMemoryDocSection = (content: string, profile: MemoryDocProfile, sectionId: string, oldText: string, newText: string, replaceAll = false): string => {
  const parsed = parseMemoryDoc(content, profile)
  const section = parsed.sections.find((item) => item.sectionId === sectionId)
  if (!section) {
    throw new SocratesError("memory_doc_section_not_found", `Section ${sectionId} was not found in ${profile.path}.`, {
      recoverable: true,
      details: { path: profile.path, sectionId },
    })
  }
  const occurrences = oldText.length === 0 ? 0 : countOccurrences(section.content, oldText)
  if (oldText.length === 0 || occurrences === 0) {
    throw new SocratesError("memory_doc_section_patch_failed", `oldText was not found in section ${sectionId}.`, {
      recoverable: true,
      details: { path: profile.path, sectionId },
    })
  }
  if (!replaceAll && occurrences > 1) {
    throw new SocratesError("memory_doc_section_patch_ambiguous", "oldText matched more than once in the selected section. Retry with a longer oldText or replaceAll=true.", {
      recoverable: true,
      details: { path: profile.path, sectionId, occurrences },
    })
  }
  const lines = content.split(/\r?\n/)
  const sectionLines = lines.slice(section.lineStart, section.lineEnd - 1)
  const currentSection = sectionLines.join("\n")
  const nextSection = replaceAll ? currentSection.split(oldText).join(newText) : currentSection.replace(oldText, newText)
  lines.splice(section.lineStart, section.lineEnd - section.lineStart - 1, ...nextSection.split("\n"))
  const next = lines.join("\n")
  const reparsed = parseMemoryDoc(next, profile)
  if (!isValidStructuredMemoryDoc(reparsed, profile.docType)) {
    throw new SocratesError("memory_doc_invalid_after_patch", "Section patch would leave the memory doc structurally invalid.", {
      recoverable: true,
      details: { path: profile.path, sectionId, warnings: reparsed.warnings },
    })
  }
  return next.endsWith("\n") ? next : `${next}\n`
}

export const stampMemoryDocFrontmatter = (
  content: string,
  stamp: { updatedAt: string; updatedBy: MemoryDocOwnerTool | "system"; lastEditedSection?: string },
): string => {
  const normalized = content.replace(/\r\n/g, "\n")
  const entries = [
    ["updated_at", stamp.updatedAt],
    ["updated_by", stamp.updatedBy],
    ...(stamp.lastEditedSection ? ([["last_edited_section", stamp.lastEditedSection]] as const) : []),
  ] as const
  if (!normalized.startsWith("---\n")) {
    return [
      "---",
      ...entries.map(([key, value]) => `${key}: ${quoteYamlScalar(value)}`),
      "---",
      "",
      normalized,
    ].join("\n")
  }
  const end = normalized.indexOf("\n---\n", 4)
  if (end < 0) {
    return normalized
  }
  const raw = normalized.slice(4, end)
  const body = normalized.slice(end + "\n---\n".length)
  let lines = raw.split("\n")
  for (const [key, value] of entries) {
    const nextLine = `${key}: ${quoteYamlScalar(value)}`
    const index = lines.findIndex((line) => line.trim().startsWith(`${key}:`))
    if (index >= 0) {
      lines[index] = nextLine
    } else {
      lines = [...lines, nextLine]
    }
  }
  return `---\n${lines.join("\n")}\n---\n${body}`
}

export const memoryDocTypeForRepoDoc = (name: string): MemoryDocType => {
  switch (name) {
    case "CORE_IDEA.md":
      return "repo_core_idea"
    case "REPO_NAVIGATION.md":
      return "repo_navigation"
    case "REPO_RULES.md":
      return "repo_rules"
    case "CONTRACTS.md":
      return "repo_contracts"
    default:
      throw new SocratesError("repo_doc_type_unknown", `Unknown repo doc ${name}.`, { recoverable: true, details: { name } })
  }
}

export const memoryDocTypeForEditFilesTarget = (target: string): MemoryDocType => {
  if (target === "identity" || target === "operating_principles" || target === "user_profile") {
    return memoryDocTypeSchema.parse(target)
  }
  if (target === "tool_doc") {
    return "tool_doc"
  }
  return "skill"
}

const isValidStructuredMemoryDoc = (index: MemoryDocIndex, docType: MemoryDocType): boolean => {
  if (index.warnings?.some((warning) => warning.startsWith("Missing required section") || warning.toLowerCase().includes("frontmatter"))) {
    return false
  }
  const required = memoryDocRequiredSections[docType]
  const sectionIds = new Set(index.sections.map((section) => section.sectionId))
  return required.every((sectionId) => sectionIds.has(sectionId))
}

const renderSection = (section: SectionDefinition): string =>
  [
    `<!-- socrates:section id="${section.id}" kind="${section.kind}" tags="${(section.tags ?? []).join(",")}" -->`,
    `## ${section.heading}`,
    "",
    section.body ?? "",
    "<!-- /socrates:section -->",
    "",
  ].join("\n")

const parseSections = (body: string, lineOffset: number): MemoryDocSection[] => {
  const lines = body.split(/\r?\n/)
  const sections: MemoryDocSection[] = []
  const seen = new Set<string>()
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? ""
    const open = /^<!--\s*socrates:section\s+(.+?)\s*-->\s*$/.exec(line)
    if (!open) {
      continue
    }
    const attributes = parseAttributes(open[1] ?? "")
    const sectionId = attributes.id
    if (!sectionId) {
      throw new SocratesError("memory_doc_section_invalid", "Socrates section marker is missing an id.", { recoverable: true, details: { line: index + 1 + lineOffset } })
    }
    if (seen.has(sectionId)) {
      throw new SocratesError("memory_doc_section_duplicate", `Duplicate Socrates section id ${sectionId}.`, { recoverable: true, details: { sectionId } })
    }
    seen.add(sectionId)
    const closeIndex = lines.findIndex((candidate, candidateIndex) => candidateIndex > index && /^<!--\s*\/socrates:section\s*-->\s*$/.test(candidate))
    if (closeIndex < 0) {
      throw new SocratesError("memory_doc_section_unclosed", `Socrates section ${sectionId} is missing a closing marker.`, { recoverable: true, details: { sectionId } })
    }
    const contentLines = lines.slice(index + 1, closeIndex)
    const content = contentLines.join("\n").trimEnd()
    sections.push({
      sectionId,
      kind: attributes.kind || "general",
      tags: (attributes.tags ?? "").split(",").map((tag) => tag.trim()).filter(Boolean),
      heading: firstHeading(content) ?? sectionId,
      content,
      lineStart: index + 1 + lineOffset,
      lineEnd: closeIndex + 1 + lineOffset,
      contentHash: hashText(content),
      summary: summarizeSection(content),
      tokenEstimate: estimateTokens(content),
    })
    index = closeIndex
  }
  return sections
}

const parseFrontmatter = (content: string): { data: Record<string, unknown>; body: string; bodyLineOffset: number } | undefined => {
  const normalized = content.replace(/\r\n/g, "\n")
  if (!normalized.startsWith("---\n")) {
    return undefined
  }
  const end = normalized.indexOf("\n---\n", 4)
  if (end < 0) {
    return undefined
  }
  const raw = normalized.slice(4, end)
  const body = normalized.slice(end + "\n---\n".length)
  const data: Record<string, unknown> = {}
  for (const line of raw.split("\n")) {
    const match = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line.trim())
    if (!match) {
      continue
    }
    const key = match[1]!
    const value = match[2] ?? ""
    if (/^\d+$/.test(value)) {
      data[key] = Number(value)
    } else if (value.startsWith("[") && value.endsWith("]")) {
      data[key] = value.slice(1, -1).split(",").map((item) => item.trim()).filter(Boolean)
    } else {
      data[key] = value.replace(/^["']|["']$/g, "")
    }
  }
  return { data, body, bodyLineOffset: raw.split("\n").length + 2 }
}

const parseAttributes = (raw: string): Record<string, string> => {
  const attributes: Record<string, string> = {}
  const pattern = /([A-Za-z0-9_-]+)="([^"]*)"/g
  let match: RegExpExecArray | null
  while ((match = pattern.exec(raw)) !== null) {
    attributes[match[1]!] = match[2] ?? ""
  }
  return attributes
}

const quoteYamlScalar = (value: string): string => `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`

const firstHeading = (content: string): string | undefined => {
  const line = content.split(/\r?\n/).find((item) => /^#{1,6}\s+/.test(item))
  return line?.replace(/^#{1,6}\s+/, "").trim()
}

const summarizeSection = (content: string): string => {
  const lines = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"))
    .slice(0, 3)
  const summary = lines.join(" ").replace(/\s+/g, " ").trim()
  return summary.length > 240 ? `${summary.slice(0, 237)}...` : summary
}

const titleForDocType = (docType: MemoryDocType): string =>
  docType
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ")

const titleForProfile = (profile: MemoryDocProfile): string => {
  if (profile.docType === "tool_doc") {
    const name = path.basename(profile.path, ".md").replace(/[_-]+/g, " ").trim()
    return `${name || "Tool"} Usage Guide`
  }
  return titleForDocType(profile.docType)
}

const hashText = (text: string): string => createHash("sha256").update(text).digest("hex")
const estimateTokens = (text: string): number => Math.ceil(text.length / 4)
const countOccurrences = (text: string, needle: string): number => text.split(needle).length - 1
