import { createHash } from "node:crypto"
import fs from "node:fs"
import path from "node:path"
import {
  memoryDocFrontmatterSchema,
  memoryDocRequiredSections,
  memoryDocTypeSchema,
  type MemoryDocIndex,
  type MemoryDocFrontmatter,
  type MemoryDocOwnerTool,
  type MemoryDocScope,
  type MemoryDocSection,
  type MemoryDocType,
  type EditFilesTarget,
} from "@socrates/contracts"
import { SocratesError } from "@socrates/shared"

export type MemoryDocProfile = {
  docType: MemoryDocType
  ownerTool: MemoryDocOwnerTool
  scope: MemoryDocScope
  path: string
  projectId?: string
  indexTags?: string[]
}

type SectionDefinition = {
  id: string
  kind: string
  heading: string
  tags?: string[]
  body?: string
}

const STATE_LEDGER_START = "<!-- socrates-state-ledger:start -->"
const STATE_LEDGER_END = "<!-- socrates-state-ledger:end -->"

const sectionDefinitions: Record<MemoryDocType, SectionDefinition[]> = {
  project_memory: [
    { id: "current_state", kind: "state", heading: "Current State", tags: ["handoff", "status"], body: "- Current project standing belongs here." },
    { id: "durable_decisions", kind: "decisions", heading: "Durable Decisions", tags: ["architecture"], body: "- Stable decisions that should survive across chats belong here." },
    { id: "constraints", kind: "constraints", heading: "Constraints", tags: ["rules"], body: "- Durable project constraints belong here." },
    { id: "project_preferences", kind: "preferences", heading: "Project Preferences", tags: ["user"], body: "- Project-specific user preferences belong here." },
    { id: "blockers", kind: "blockers", heading: "Blockers", tags: ["handoff"], body: "- Long-lived blockers belong here." },
    { id: "handoff", kind: "handoff", heading: "Handoff", tags: ["restart"], body: "- Restart-ready handoff facts belong here." },
    { id: "evidence_anchors", kind: "anchors", heading: "Evidence Anchors", tags: ["source"], body: "- Exact evidence pointers belong here." },
  ],
  project_notes: [
    {
      id: "runtime_context",
      kind: "system",
      heading: "Runtime Context",
      tags: ["runtime", "generated", "system"],
      body: [
        "system_owned: true",
        "generated_at: never",
        "signature: none",
        "workspace:",
        "  root: unknown",
        "python:",
        "  virtual_environments:",
        "    - none",
        "  dependency_files:",
        "    - none",
        "  package_managers:",
        "    - none",
        "terminal_state: omitted",
        "notes:",
        "  - Runtime workspace scan facts are generated by the backend.",
        "  - Terminal output and live terminal state are intentionally not persisted here.",
      ].join("\n"),
    },
    {
      id: "state_ledger",
      kind: "state",
      heading: "State Ledger",
      tags: ["machine", "startup"],
      body: [
        STATE_LEDGER_START,
        "## Socrates State Ledger",
        "",
        "Machine-managed compact state for startup context. Preserve this bounded section; human notes can live outside it.",
        "",
        "- Updated: never",
        "- Last turn: none",
        "- Recent tools: none",
        "- Files touched: none",
        "- Commands: none",
        "- Startup hint: read full project notes with project_docs({operation:\"read\", area:\"notes\"}) when more detail is needed.",
        STATE_LEDGER_END,
      ].join("\n"),
    },
    { id: "active_todos", kind: "todos", heading: "Active Todos", tags: ["work"], body: "- Active todos belong here." },
    { id: "checked_files", kind: "files", heading: "Checked Files", tags: ["work"], body: "- Files already checked belong here." },
    { id: "next_commands", kind: "commands", heading: "Next Commands", tags: ["work"], body: "- Next useful commands belong here." },
    { id: "scratch_notes", kind: "scratch", heading: "Scratch Notes", tags: ["temporary"], body: "- Temporary investigation notes belong here." },
    { id: "completed_archive", kind: "archive", heading: "Completed Archive", tags: ["history"], body: "- Completed short-term notes can be condensed here." },
  ],
  repo_core_idea: [
    { id: "purpose", kind: "purpose", heading: "Purpose", tags: ["overview"], body: "- What this workspace is for:" },
    { id: "current_direction", kind: "state", heading: "Current Direction", tags: ["status"], body: "- Current priority:" },
    { id: "milestones", kind: "milestones", heading: "Milestones", tags: ["planning"], body: "- Next durable milestone:" },
    { id: "update_triggers", kind: "rules", heading: "Update Triggers", tags: ["maintenance"], body: "- Update when purpose, phase, or direction changes." },
  ],
  repo_navigation: [
    { id: "ownership_map", kind: "navigation", heading: "Ownership Map", tags: ["files"], body: "- Important folders:" },
    { id: "entry_points", kind: "navigation", heading: "Entry Points", tags: ["files"], body: "- Entry points:" },
    { id: "tests", kind: "testing", heading: "Tests", tags: ["verification"], body: "- Test locations:" },
    { id: "generated_ignored", kind: "navigation", heading: "Generated And Ignored Areas", tags: ["files"], body: "- Generated or ignored output:" },
    { id: "navigation_rules", kind: "rules", heading: "Navigation Rules", tags: ["workflow"], body: "- Where to look first:" },
  ],
  repo_rules: [
    { id: "hard_rules", kind: "rules", heading: "Hard Rules", tags: ["constraints"], body: "- Preserve user work; do not revert unrelated changes." },
    { id: "workflows", kind: "workflow", heading: "Workflows", tags: ["process"], body: "- Preferred workflows belong here." },
    { id: "verification", kind: "verification", heading: "Verification", tags: ["tests"], body: "- Verify meaningful changes with the narrowest reliable check." },
    { id: "known_pitfalls", kind: "pitfalls", heading: "Known Pitfalls", tags: ["risk"], body: "- Recurring mistakes belong here." },
    { id: "update_triggers", kind: "rules", heading: "Update Triggers", tags: ["maintenance"], body: "- Update when stable repo conventions or verification workflows change." },
  ],
  repo_contracts: [
    { id: "tool_contracts", kind: "contracts", heading: "Tool Contracts", tags: ["tools"], body: "- Tool input/output contracts:" },
    { id: "api_contracts", kind: "contracts", heading: "API Contracts", tags: ["api"], body: "- API routes:" },
    { id: "db_event_contracts", kind: "contracts", heading: "Database And Event Contracts", tags: ["db", "events"], body: "- Persistence invariants:" },
    { id: "frontend_backend", kind: "contracts", heading: "Frontend Backend Responsibilities", tags: ["frontend", "backend"], body: "- UI/runtime expectations:" },
    { id: "change_log", kind: "changes", heading: "Change Log", tags: ["maintenance"], body: "- Contract changes belong here." },
  ],
  identity: [
    {
      id: "core_identity",
      kind: "identity",
      heading: "Core Identity",
      tags: ["soul"],
      body: [
        "- Socrates is a local-first project partner.",
        "- Socrates works from evidence in the current workspace, repo docs, tool traces, and explicit user instructions.",
      ].join("\n"),
    },
    { id: "voice_and_presence", kind: "style", heading: "Voice And Presence", tags: ["soul"], body: "- Be direct, concrete, technically grounded, and emotionally present without becoming theatrical." },
    {
      id: "relationship_to_user",
      kind: "relationship",
      heading: "Relationship To User",
      tags: ["soul"],
      body: "- Work as a durable project partner for one user.\n- Durable user profile and stable cross-project preferences live in `user_profile.md` and are accessed through the `user_profile` tool.",
    },
    { id: "operating_principles", kind: "principles", heading: "Operating Principles", tags: ["behavior"], body: "- Prefer evidence over assumption.\n- Gather enough context before changing files.\n- Keep project-specific state inside the workspace `.socrates/` tree." },
    { id: "safety_boundaries", kind: "safety", heading: "Safety Boundaries", tags: ["soul", "safety"], body: "- Runtime, developer, and user instructions outrank this file.\n- Do not store secrets, credentials, private keys, or sensitive raw data.\n- Stop and ask before destructive or sensitive actions without explicit instruction." },
    { id: "tool_and_memory_discipline", kind: "tools", heading: "Tool And Memory Discipline", tags: ["tools", "memory"], body: "- Use dedicated docs and memory tools for Socrates-owned docs instead of generic file tools.\n- Update identity only from explicit user statements or repeated behavior with clear support in traces.\n- Prefer small section edits over broad rewrites." },
  ],
  user_profile: [
    { id: "profile_summary", kind: "profile", heading: "Profile Summary", tags: ["user"], body: "- No stable profile facts captured yet." },
    { id: "stable_preferences", kind: "preferences", heading: "Stable Preferences", tags: ["user"], body: "- No durable cross-project preferences captured yet." },
    { id: "collaboration_style", kind: "style", heading: "Collaboration Style", tags: ["user"], body: "- Prefer direct, concrete, technically grounded communication." },
    { id: "work_and_projects", kind: "work", heading: "Work And Projects", tags: ["user", "projects"], body: "- No durable cross-project work context captured yet." },
    { id: "personal_interests", kind: "interests", heading: "Personal Interests", tags: ["user"], body: "- No durable personal interests captured yet." },
    { id: "boundaries_and_dislikes", kind: "boundaries", heading: "Boundaries And Dislikes", tags: ["user"], body: "- Do not store secrets, credentials, private keys, or sensitive raw data.\n- Strong dislikes or boundaries belong here when explicitly stated." },
    { id: "recent_context", kind: "recent", heading: "Recent Context", tags: ["user", "recency"], body: "- No short-lived cross-project personal context captured yet." },
    { id: "evidence_index", kind: "evidence", heading: "Evidence Index", tags: ["user", "evidence"], body: "- No compact source anchors captured yet." },
  ],
  tool_doc: [
    { id: "purpose", kind: "purpose", heading: "Purpose", tags: ["tools"], body: "- Describe what this tool guidance is for." },
    { id: "when_to_use", kind: "routing", heading: "When To Use", tags: ["tools"], body: "- Describe when to call this tool." },
    { id: "inputs", kind: "schema", heading: "Inputs", tags: ["tools"], body: "- Describe important inputs and constraints." },
    { id: "workflow", kind: "workflow", heading: "Workflow", tags: ["tools"], body: "- Describe the preferred tool flow." },
    { id: "failure_handling", kind: "recovery", heading: "Failure Handling", tags: ["tools"], body: "- Describe how to recover from common failures." },
  ],
  skill: [
    { id: "purpose", kind: "purpose", heading: "Purpose", tags: ["skills"], body: "- What this skill is for." },
    { id: "workflow", kind: "workflow", heading: "Workflow", tags: ["skills"], body: "- Steps to follow." },
    { id: "examples", kind: "examples", heading: "Examples", tags: ["skills"], body: "- Examples belong here." },
    { id: "update_policy", kind: "rules", heading: "Update Policy", tags: ["skills"], body: "- Update when the reusable workflow changes." },
  ],
}

export const parseMemoryDoc = (content: string, profile: MemoryDocProfile): MemoryDocIndex => {
  const parsedFrontmatter = parseFrontmatter(content)
  const warnings: string[] = []
  let body = content
  let frontmatter: MemoryDocFrontmatter = {
    socrates_doc: profile.docType,
    schema_version: 1,
    owner_tool: profile.ownerTool,
    scope: profile.scope,
  }
  if (profile.indexTags && profile.indexTags.length > 0) {
    frontmatter = { ...frontmatter, index_tags: profile.indexTags }
  }
  let bodyLineOffset = 0
  if (parsedFrontmatter) {
    body = parsedFrontmatter.body
    bodyLineOffset = parsedFrontmatter.bodyLineOffset
    const validated = memoryDocFrontmatterSchema.safeParse(parsedFrontmatter.data)
    if (validated.success) {
      frontmatter = validated.data
      if (frontmatter.socrates_doc !== profile.docType) {
        warnings.push(`Frontmatter doc type ${frontmatter.socrates_doc} did not match expected ${profile.docType}.`)
      }
      if (frontmatter.owner_tool !== profile.ownerTool) {
        warnings.push(`Frontmatter owner ${frontmatter.owner_tool} did not match expected ${profile.ownerTool}.`)
      }
      if (frontmatter.scope !== profile.scope) {
        warnings.push(`Frontmatter scope ${frontmatter.scope} did not match expected ${profile.scope}.`)
      }
    } else {
      warnings.push("Frontmatter was present but did not match the Socrates memory-doc schema.")
    }
  } else {
    warnings.push("Document has no Socrates memory-doc frontmatter.")
  }

  const sections = parseSections(body, bodyLineOffset)
  const required = memoryDocRequiredSections[profile.docType]
  const existing = new Set(sections.map((section) => section.sectionId))
  for (const requiredSection of required) {
    if (!existing.has(requiredSection)) {
      warnings.push(`Missing required section ${requiredSection}.`)
    }
  }

  return {
    path: profile.path,
    scope: profile.scope,
    ...(profile.projectId ? { projectId: profile.projectId } : {}),
    docType: profile.docType,
    ownerTool: profile.ownerTool,
    schemaVersion: frontmatter.schema_version,
    contentHash: hashText(content),
    sections,
    ...(warnings.length > 0 ? { warnings } : {}),
  }
}

export const ensureStructuredMemoryDoc = (filePath: string, profile: MemoryDocProfile): void => {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, buildStructuredMemoryDoc(profile))
    return
  }
  const current = fs.readFileSync(filePath, "utf8")
  try {
    const parsed = parseMemoryDoc(current, profile)
    if (isValidStructuredMemoryDoc(parsed, profile.docType, current)) {
      return
    }
  } catch {
    // Preserve the original text in a legacy section instead of failing startup on a malformed doc.
  }
  if (profile.docType === "identity" || profile.docType === "user_profile") {
    fs.writeFileSync(filePath, buildStructuredMemoryDoc(profile, { sectionBodies: sectionBodiesForPrimaryDocMigration(current, profile) }))
    return
  }
  fs.writeFileSync(filePath, buildStructuredMemoryDoc(profile, { legacyContent: current }))
}

export const buildStructuredMemoryDoc = (profile: MemoryDocProfile, options: { legacyContent?: string; sectionBodies?: Record<string, string> } = {}): string => {
  const title = titleForProfile(profile)
  const frontmatter = [
    "---",
    `socrates_doc: ${profile.docType}`,
    "schema_version: 1",
    `owner_tool: ${profile.ownerTool}`,
    `scope: ${profile.scope}`,
    profile.indexTags && profile.indexTags.length > 0 ? `index_tags: [${profile.indexTags.join(", ")}]` : undefined,
    "---",
    "",
  ].filter((line): line is string => typeof line === "string")
  const sections = sectionDefinitions[profile.docType].map((section) => renderSection({ ...section, body: options.sectionBodies?.[section.id]?.trim() || section.body }))
  const legacy = options.legacyContent?.trim()
  if (legacy) {
    sections.push(
      renderSection({
        id: "legacy_content",
        kind: "legacy",
        heading: "Legacy Content",
        tags: ["migration"],
        body: legacy,
      }),
    )
  }
  return [...frontmatter, `# ${title}`, "", ...sections].join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n"
}

const sectionBodiesForPrimaryDocMigration = (content: string, profile: MemoryDocProfile): Record<string, string> => {
  const defaults = Object.fromEntries(sectionDefinitions[profile.docType].map((section) => [section.id, section.body]))
  const buckets: Record<string, string[]> = {}
  const add = (sectionId: string, body: string): void => {
    const trimmed = body.trim()
    if (!trimmed) {
      return
    }
    buckets[sectionId] = [...(buckets[sectionId] ?? []), trimmed]
  }
  const entries = existingSectionEntries(content, profile)
  const fallbackSection = profile.docType === "identity" ? "core_identity" : "profile_summary"
  if (entries.length === 0) {
    add(fallbackSection, markdownBodyWithoutFrontmatterAndTitle(content))
  }
  for (const entry of entries) {
    for (const expanded of primaryDocMigrationEntries(entry, profile.docType)) {
      add(sectionIdForMigratedEntry(profile.docType, expanded.id, expanded.heading), expanded.body)
    }
  }
  for (const section of sectionDefinitions[profile.docType]) {
    const migrated = buckets[section.id] ?? []
    if (migrated.length > 0) {
      defaults[section.id] = cleanPrimarySectionBody(profile.docType, section.id, Array.from(new Set(migrated)).join("\n\n"))
    }
  }
  return defaults
}

const existingSectionEntries = (content: string, profile: MemoryDocProfile): Array<{ id?: string; heading?: string; body: string }> => {
  try {
    const parsed = parseMemoryDoc(content, profile)
    if (parsed.sections.length > 0) {
      return parsed.sections.map((section) => ({ id: section.sectionId, heading: section.heading, body: section.content }))
    }
  } catch {
    // Fall through to tolerant extraction. Primary docs can contain nested or
    // duplicate section markers from older migrations; strict parsing must not
    // make startup unrecoverable.
  }
  const tolerantEntries = tolerantSectionMarkerEntries(content)
  if (tolerantEntries.length > 0) {
    return tolerantEntries
  }
  return markdownHeadingEntries(content)
}

const tolerantSectionMarkerEntries = (content: string): Array<{ id?: string; heading?: string; body: string }> => {
  const body = markdownBodyWithoutFrontmatterAndTitle(content)
  const lines = body.split(/\r?\n/)
  const stack: Array<{ id?: string; start: number }> = []
  const entries: Array<{ id?: string; heading?: string; body: string }> = []
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? ""
    const open = /^<!--\s*socrates:section\s+(.+?)\s*-->\s*$/.exec(line)
    if (open) {
      const attributes = parseAttributes(open[1] ?? "")
      stack.push({ id: attributes.id, start: index + 1 })
      continue
    }
    if (!/^<!--\s*\/socrates:section\s*-->\s*$/.test(line)) {
      continue
    }
    const entry = stack.pop()
    if (!entry) {
      continue
    }
    const entryBody = lines.slice(entry.start, index).join("\n").trim()
    const heading = firstHeading(entryBody)
    if (entryBody) {
      entries.push({ id: entry.id, ...(heading ? { heading } : {}), body: entryBody })
    }
  }
  return entries
}

const primaryDocMigrationEntries = (entry: { id?: string; heading?: string; body: string }, docType: "identity" | "user_profile"): Array<{ id?: string; heading?: string; body: string }> => {
  const nested = markdownHeadingEntries(entry.body)
  if (nested.length === 0) {
    return [{ id: entry.id, heading: entry.heading, body: cleanPrimaryMigrationBody(entry.body) }].filter((item) => item.body.trim().length > 0)
  }
  const expanded: Array<{ id?: string; heading?: string; body: string }> = []
  for (const nestedEntry of nested) {
    const key = normalizeSectionKey(nestedEntry.heading)
    if (isPrimaryMigrationWrapperHeading(key)) {
      continue
    }
    const body = cleanPrimaryMigrationBody(nestedEntry.body)
    if (body.trim()) {
      expanded.push({ heading: nestedEntry.heading, body })
    }
  }
  if (expanded.length > 0) {
    return expanded
  }
  return [{ id: entry.id, heading: entry.heading, body: cleanPrimaryMigrationBody(entry.body) }].filter((item) => item.body.trim().length > 0)
}

const isPrimaryMigrationWrapperHeading = (key: string): boolean =>
  ["legacycontent", "migratedfromidentitymd", "migratedfromidentity", "migratedfrom"].includes(key)

const cleanPrimaryMigrationBody = (body: string): string =>
  dedupeMarkdownLines(
    body
      .replace(/<!--\s*\/?socrates:section\b[^>]*-->/gi, "")
      .split(/\r?\n/)
      .filter((line) => {
        const trimmed = line.trim()
        if (/^#{1,6}\s+/.test(trimmed)) return false
        if (trimmed === "---") return false
        if (/^(socrates_doc|schema_version|owner_tool|scope|index_tags|updated_at|updated_by|last_edited_section):\s*/i.test(trimmed)) return false
        return true
      })
      .join("\n"),
  )

const cleanPrimarySectionBody = (docType: "identity" | "user_profile", sectionId: string, body: string): string => {
  const lines = dedupeMarkdownLines(body).split(/\r?\n/)
  const hasSpecificLine = lines.some((line) => {
    const trimmed = line.trim()
    return trimmed.length > 0 && !isPrimaryBoilerplateLine(trimmed, docType, sectionId)
  })
  if (!hasSpecificLine) {
    return sectionDefinitions[docType].find((section) => section.id === sectionId)?.body ?? dedupeMarkdownLines(body)
  }
  return compactPrimarySectionBody(docType, sectionId, lines.filter((line) => !isPrimaryBoilerplateLine(line.trim(), docType, sectionId)).join("\n"))
}

const dedupeMarkdownLines = (body: string): string => {
  const seen = new Set<string>()
  const result: string[] = []
  let previousWasBlank = false
  for (const line of body.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed) {
      if (!previousWasBlank) {
        result.push("")
      }
      previousWasBlank = true
      continue
    }
    previousWasBlank = false
    const key = trimmed.replace(/\s+/g, " ")
    if (seen.has(key)) {
      continue
    }
    seen.add(key)
    result.push(line)
  }
  return result.join("\n").replace(/\n{3,}/g, "\n\n").trim()
}

const isPrimaryBoilerplateLine = (line: string, docType: "identity" | "user_profile", sectionId: string): boolean => {
  if (!line) return false
  const normalized = line.toLowerCase().replace(/\s+/g, " ")
  if (docType === "user_profile") {
    return [
      "root global user profile for socrates. runtime, developer, and user instructions outrank this file.",
      "- unknown until repeated or explicit evidence justifies a durable note.",
      "- keep this section narrow. store only durable preferences that should transfer across projects.",
      "- durable cross-project preferences belong here.",
      "- durable cross-project work context belongs here.",
      "- durable personal interests belong here only when explicit or repeatedly useful.",
      "- short-lived but useful cross-project personal context belongs here and should be refreshed or removed as it ages.",
      "- record compact evidence anchors for important profile claims: dates, project names, conversation titles, or short source descriptions.",
      "- superseded or rejected profile facts belong here.",
      "- update only from explicit user statements or repeated behavior with clear support in traces.",
      "- prefer small bullet edits inside existing sections over broad rewrites.",
      "- update only from explicit statements or repeated behavior with clear support in traces.",
    ].includes(normalized)
  }
  if (docType === "identity" && sectionId === "core_identity") {
    return ["root global identity for socrates. runtime, developer, and user instructions outrank this file."].includes(normalized)
  }
  return false
}

const compactPrimarySectionBody = (docType: "identity" | "user_profile", sectionId: string, body: string): string => {
  const lines = dedupeMarkdownLines(body).split(/\r?\n/)
  const keyToOutputIndex = new Map<string, number>()
  const output: string[] = []
  for (const line of lines) {
    const key = primarySemanticLineKey(docType, sectionId, line)
    if (!key) {
      output.push(line)
      continue
    }
    const existingIndex = keyToOutputIndex.get(key)
    if (existingIndex === undefined) {
      keyToOutputIndex.set(key, output.length)
      output.push(line)
      continue
    }
    if (line.length > (output[existingIndex]?.length ?? 0)) {
      output[existingIndex] = line
    }
  }
  return dedupeMarkdownLines(output.join("\n"))
}

const primarySemanticLineKey = (docType: "identity" | "user_profile", sectionId: string, line: string): string | undefined => {
  const trimmed = line.trim()
  if (!trimmed || !trimmed.startsWith("-")) {
    return undefined
  }
  const boldLabel = /^-\s+\*\*(.+?)\*\*\s*:/.exec(trimmed)
  if (boldLabel) {
    const labelKey = normalizeSectionKey(boldLabel[1])
    if (docType === "user_profile") {
      if (sectionId === "profile_summary" && labelKey === "primaryproject") return `${docType}:${sectionId}:primaryproject`
      if (sectionId === "stable_preferences") {
        if (labelKey === "communicationstyle") return `${docType}:${sectionId}:communicationstyle`
        if (labelKey === "taskguidance") return `${docType}:${sectionId}:taskguidance`
        if (labelKey === "toolusage") return `${docType}:${sectionId}:toolusage`
        if (labelKey === "storage") return `${docType}:${sectionId}:storage`
      }
    }
    return `${docType}:${sectionId}:label:${labelKey}`
  }
  const normalized = trimmed.toLowerCase().replace(/[`*_]/g, "").replace(/\s+/g, " ")
  if (docType === "user_profile") {
    if (sectionId === "profile_summary" && normalized.includes("primary project")) return `${docType}:${sectionId}:primaryproject`
    if (sectionId === "stable_preferences") {
      if (normalized.includes("casual") && normalized.includes("informal")) return `${docType}:${sectionId}:communicationstyle`
      if (normalized.includes("step-by-step") || normalized.includes("step by step")) return `${docType}:${sectionId}:taskguidance`
      if (normalized.includes("tests tools extensively")) return `${docType}:${sectionId}:toolusage`
      if (normalized.includes("onedrive") || normalized.includes("icloud")) return `${docType}:${sectionId}:storage`
    }
    if (sectionId === "collaboration_style" && normalized.includes("prefer direct") && normalized.includes("concrete")) return `${docType}:${sectionId}:directconcrete`
  }
  return undefined
}

const sectionIdForMigratedEntry = (docType: "identity" | "user_profile", id: string | undefined, heading: string | undefined): string => {
  const key = normalizeSectionKey(id || heading || "")
  if (docType === "identity") {
    if (["identity", "role", "coreidentity", "coreidentity"].includes(key)) return "core_identity"
    if (["voice", "style", "voiceandpresence"].includes(key)) return "voice_and_presence"
    if (["usercontext", "relationship", "relationshiptouser"].includes(key)) return "relationship_to_user"
    if (["decisionprinciples", "tooluse", "updates", "operatingprinciples", "principles"].includes(key)) return "operating_principles"
    if (["scope", "nonnegotiables", "boundaries", "safety", "safetyboundaries"].includes(key)) return "safety_boundaries"
    if (["changepolicy", "evidencerequirements", "tooldiscipline", "memorydiscipline", "toolandmemorydiscipline"].includes(key)) return "tool_and_memory_discipline"
    return "core_identity"
  }
  if (["profile", "stablefacts", "profilesummary", "userprofile"].includes(key)) return "profile_summary"
  if (["stablepreferences", "preferences"].includes(key)) return "stable_preferences"
  if (["collaborationstyle", "style"].includes(key)) return "collaboration_style"
  if (["work", "projects", "workandprojects"].includes(key)) return "work_and_projects"
  if (["interests", "personalinterests", "hobbies"].includes(key)) return "personal_interests"
  if (["boundaries", "dislikes", "boundariesanddislikes"].includes(key)) return "boundaries_and_dislikes"
  if (["recent", "recentcontext"].includes(key)) return "recent_context"
  if (["evidence", "evidencerequirements", "evidenceindex", "staleorrejectedfacts"].includes(key)) return "evidence_index"
  return "profile_summary"
}

const markdownHeadingEntries = (content: string): Array<{ heading: string; body: string }> => {
  const body = markdownBodyWithoutFrontmatterAndTitle(content)
  const matches = Array.from(body.matchAll(/^##\s+(.+?)\s*$/gm))
  if (matches.length === 0) {
    return []
  }
  return matches.map((match, index) => {
    const start = (match.index ?? 0) + match[0].length
    const end = index + 1 < matches.length ? matches[index + 1].index ?? body.length : body.length
    return { heading: match[1].trim(), body: body.slice(start, end).trim() }
  })
}

const markdownBodyWithoutFrontmatterAndTitle = (content: string): string => {
  let body = content.trim()
  if (body.startsWith("---")) {
    const end = body.indexOf("\n---", 3)
    if (end >= 0) {
      body = body.slice(end + 4).trim()
    }
  }
  return body.replace(/^#\s+.+\s*/m, "").trim()
}

const normalizeSectionKey = (value: string): string => value.toLowerCase().replace(/[^a-z0-9]/g, "")

export const patchMemoryDocSection = (content: string, profile: MemoryDocProfile, sectionId: string, oldText: string, newText: string, replaceAll = false): string => {
  const parsed = parseMemoryDoc(content, profile)
  const section = parsed.sections.find((item) => item.sectionId === sectionId)
  if (!section) {
    throw new SocratesError("memory_doc_section_not_found", `Section ${sectionId} was not found in ${profile.path}.`, {
      recoverable: true,
      details: { path: profile.path, sectionId },
    })
  }
  const occurrences = oldText.length === 0 ? 0 : countOccurrences(section.content, oldText)
  if (oldText.length === 0 || occurrences === 0) {
    throw new SocratesError("memory_doc_section_patch_failed", `oldText was not found in section ${sectionId}.`, {
      recoverable: true,
      details: { path: profile.path, sectionId },
    })
  }
  if (!replaceAll && occurrences > 1) {
    throw new SocratesError("memory_doc_section_patch_ambiguous", "oldText matched more than once in the selected section. Retry with a longer oldText or replaceAll=true.", {
      recoverable: true,
      details: { path: profile.path, sectionId, occurrences },
    })
  }
  const lines = content.split(/\r?\n/)
  const sectionLines = lines.slice(section.lineStart, section.lineEnd - 1)
  const currentSection = sectionLines.join("\n")
  const nextSection = replaceAll ? currentSection.split(oldText).join(newText) : currentSection.replace(oldText, newText)
  lines.splice(section.lineStart, section.lineEnd - section.lineStart - 1, ...nextSection.split("\n"))
  const next = lines.join("\n")
  const reparsed = parseMemoryDoc(next, profile)
  if (!isValidStructuredMemoryDoc(reparsed, profile.docType)) {
    throw new SocratesError("memory_doc_invalid_after_patch", "Section patch would leave the memory doc structurally invalid.", {
      recoverable: true,
      details: { path: profile.path, sectionId, warnings: reparsed.warnings },
    })
  }
  return next.endsWith("\n") ? next : `${next}\n`
}

export const stampMemoryDocFrontmatter = (
  content: string,
  stamp: { updatedAt: string; updatedBy: MemoryDocOwnerTool | "system"; lastEditedSection?: string },
): string => {
  const normalized = content.replace(/\r\n/g, "\n")
  const entries = [
    ["updated_at", stamp.updatedAt],
    ["updated_by", stamp.updatedBy],
    ...(stamp.lastEditedSection ? ([["last_edited_section", stamp.lastEditedSection]] as const) : []),
  ] as const
  if (!normalized.startsWith("---\n")) {
    return [
      "---",
      ...entries.map(([key, value]) => `${key}: ${quoteYamlScalar(value)}`),
      "---",
      "",
      normalized,
    ].join("\n")
  }
  const end = normalized.indexOf("\n---\n", 4)
  if (end < 0) {
    return normalized
  }
  const raw = normalized.slice(4, end)
  const body = normalized.slice(end + "\n---\n".length)
  let lines = raw.split("\n")
  for (const [key, value] of entries) {
    const nextLine = `${key}: ${quoteYamlScalar(value)}`
    const index = lines.findIndex((line) => line.trim().startsWith(`${key}:`))
    if (index >= 0) {
      lines[index] = nextLine
    } else {
      lines = [...lines, nextLine]
    }
  }
  return `---\n${lines.join("\n")}\n---\n${body}`
}

export const memoryDocTypeForRepoDoc = (name: string): MemoryDocType => {
  switch (name) {
    case "CORE_IDEA.md":
      return "repo_core_idea"
    case "REPO_NAVIGATION.md":
      return "repo_navigation"
    case "REPO_RULES.md":
      return "repo_rules"
    case "CONTRACTS.md":
      return "repo_contracts"
    default:
      throw new SocratesError("repo_doc_type_unknown", `Unknown repo doc ${name}.`, { recoverable: true, details: { name } })
  }
}

export const memoryDocTypeForEditFilesTarget = (target: EditFilesTarget): MemoryDocType => {
  if (target === "identity" || target === "user_profile") {
    return memoryDocTypeSchema.parse(target)
  }
  return "skill"
}

const isValidStructuredMemoryDoc = (index: MemoryDocIndex, docType: MemoryDocType, content?: string): boolean => {
  if (index.warnings?.some((warning) => warning.startsWith("Missing required section") || warning.toLowerCase().includes("frontmatter"))) {
    return false
  }
  if ((docType === "identity" || docType === "user_profile") && ((content ? primaryDocContainsLegacyContent(content) || primaryDocContainsOldBoilerplate(content) : false) || primaryDocContainsDuplicateLines(index) || primaryDocContainsSemanticDuplicates(index, docType))) {
    return false
  }
  const required = memoryDocRequiredSections[docType]
  const sectionIds = new Set(index.sections.map((section) => section.sectionId))
  return required.every((sectionId) => sectionIds.has(sectionId))
}

const primaryDocContainsLegacyContent = (content: string): boolean => /id="legacy_content"|##\s+Legacy Content\b|#\s+Legacy Content\b/i.test(content)

const primaryDocContainsOldBoilerplate = (content: string): boolean =>
  /Keep this section narrow|Durable cross-project .* belongs here|Unknown until repeated|Root global user profile|Superseded or rejected profile facts belong here/i.test(content)

const primaryDocContainsDuplicateLines = (index: MemoryDocIndex): boolean =>
  index.sections.some((section) => {
    const seen = new Set<string>()
    for (const line of section.content.split(/\r?\n/)) {
      const trimmed = line.trim()
      if (!trimmed || /^##\s+/.test(trimmed)) {
        continue
      }
      const key = trimmed.replace(/\s+/g, " ")
      if (seen.has(key)) {
        return true
      }
      seen.add(key)
    }
    return false
  })

const primaryDocContainsSemanticDuplicates = (index: MemoryDocIndex, docType: MemoryDocType): boolean => {
  if (docType !== "identity" && docType !== "user_profile") {
    return false
  }
  return index.sections.some((section) => {
    const seen = new Set<string>()
    for (const line of section.content.split(/\r?\n/)) {
      const key = primarySemanticLineKey(docType, section.sectionId, line)
      if (!key) {
        continue
      }
      if (seen.has(key)) {
        return true
      }
      seen.add(key)
    }
    return false
  })
}

const renderSection = (section: SectionDefinition): string =>
  [
    `<!-- socrates:section id="${section.id}" kind="${section.kind}" tags="${(section.tags ?? []).join(",")}" -->`,
    `## ${section.heading}`,
    "",
    section.body ?? "",
    "<!-- /socrates:section -->",
    "",
  ].join("\n")

const parseSections = (body: string, lineOffset: number): MemoryDocSection[] => {
  const lines = body.split(/\r?\n/)
  const sections: MemoryDocSection[] = []
  const seen = new Set<string>()
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? ""
    const open = /^<!--\s*socrates:section\s+(.+?)\s*-->\s*$/.exec(line)
    if (!open) {
      continue
    }
    const attributes = parseAttributes(open[1] ?? "")
    const sectionId = attributes.id
    if (!sectionId) {
      throw new SocratesError("memory_doc_section_invalid", "Socrates section marker is missing an id.", { recoverable: true, details: { line: index + 1 + lineOffset } })
    }
    if (seen.has(sectionId)) {
      throw new SocratesError("memory_doc_section_duplicate", `Duplicate Socrates section id ${sectionId}.`, { recoverable: true, details: { sectionId } })
    }
    seen.add(sectionId)
    const closeIndex = lines.findIndex((candidate, candidateIndex) => candidateIndex > index && /^<!--\s*\/socrates:section\s*-->\s*$/.test(candidate))
    if (closeIndex < 0) {
      throw new SocratesError("memory_doc_section_unclosed", `Socrates section ${sectionId} is missing a closing marker.`, { recoverable: true, details: { sectionId } })
    }
    const contentLines = lines.slice(index + 1, closeIndex)
    const content = contentLines.join("\n").trimEnd()
    sections.push({
      sectionId,
      kind: attributes.kind || "general",
      tags: (attributes.tags ?? "").split(",").map((tag) => tag.trim()).filter(Boolean),
      heading: firstHeading(content) ?? sectionId,
      content,
      lineStart: index + 1 + lineOffset,
      lineEnd: closeIndex + 1 + lineOffset,
      contentHash: hashText(content),
      summary: summarizeSection(content),
      tokenEstimate: estimateTokens(content),
    })
    index = closeIndex
  }
  return sections
}

const parseFrontmatter = (content: string): { data: Record<string, unknown>; body: string; bodyLineOffset: number } | undefined => {
  const normalized = content.replace(/\r\n/g, "\n")
  if (!normalized.startsWith("---\n")) {
    return undefined
  }
  const end = normalized.indexOf("\n---\n", 4)
  if (end < 0) {
    return undefined
  }
  const raw = normalized.slice(4, end)
  const body = normalized.slice(end + "\n---\n".length)
  const data: Record<string, unknown> = {}
  for (const line of raw.split("\n")) {
    const match = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line.trim())
    if (!match) {
      continue
    }
    const key = match[1]!
    const value = match[2] ?? ""
    if (/^\d+$/.test(value)) {
      data[key] = Number(value)
    } else if (value.startsWith("[") && value.endsWith("]")) {
      data[key] = value.slice(1, -1).split(",").map((item) => item.trim()).filter(Boolean)
    } else {
      data[key] = value.replace(/^["']|["']$/g, "")
    }
  }
  return { data, body, bodyLineOffset: raw.split("\n").length + 2 }
}

const parseAttributes = (raw: string): Record<string, string> => {
  const attributes: Record<string, string> = {}
  const pattern = /([A-Za-z0-9_-]+)="([^"]*)"/g
  let match: RegExpExecArray | null
  while ((match = pattern.exec(raw)) !== null) {
    attributes[match[1]!] = match[2] ?? ""
  }
  return attributes
}

const quoteYamlScalar = (value: string): string => `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`

const firstHeading = (content: string): string | undefined => {
  const line = content.split(/\r?\n/).find((item) => /^#{1,6}\s+/.test(item))
  return line?.replace(/^#{1,6}\s+/, "").trim()
}

const summarizeSection = (content: string): string => {
  const lines = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"))
    .slice(0, 3)
  const summary = lines.join(" ").replace(/\s+/g, " ").trim()
  return summary.length > 240 ? `${summary.slice(0, 237)}...` : summary
}

const titleForDocType = (docType: MemoryDocType): string =>
  docType
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ")

const titleForProfile = (profile: MemoryDocProfile): string => {
  if (profile.docType === "tool_doc") {
    const name = path.basename(profile.path, ".md").replace(/[_-]+/g, " ").trim()
    return `${name || "Tool"} Usage Guide`
  }
  return titleForDocType(profile.docType)
}

const hashText = (text: string): string => createHash("sha256").update(text).digest("hex")
const estimateTokens = (text: string): number => Math.ceil(text.length / 4)
const countOccurrences = (text: string, needle: string): number => text.split(needle).length - 1
