/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsCreateRouteImport } from './routes/projects/create'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdDashboardRouteImport } from './routes/projects/$projectId/dashboard'
import { Route as ProjectsProjectIdConversationsConversationIdRouteImport } from './routes/projects/$projectId/conversations.$conversationId'
import { Route as ProjectsProjectIdDashboardConversationsConversationIdRouteImport } from './routes/projects/$projectId/dashboard.conversations.$conversationId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDashboardRoute =
  ProjectsProjectIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdConversationsConversationIdRoute =
  ProjectsProjectIdConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDashboardConversationsConversationIdRoute =
  ProjectsProjectIdDashboardConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => ProjectsProjectIdDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/dashboard': typeof ProjectsProjectIdDashboardRouteWithChildren
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/conversations/$conversationId': typeof ProjectsProjectIdConversationsConversationIdRoute
  '/projects/$projectId/dashboard/conversations/$conversationId': typeof ProjectsProjectIdDashboardConversationsConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/dashboard': typeof ProjectsProjectIdDashboardRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/conversations/$conversationId': typeof ProjectsProjectIdConversationsConversationIdRoute
  '/projects/$projectId/dashboard/conversations/$conversationId': typeof ProjectsProjectIdDashboardConversationsConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/dashboard': typeof ProjectsProjectIdDashboardRouteWithChildren
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/conversations/$conversationId': typeof ProjectsProjectIdConversationsConversationIdRoute
  '/projects/$projectId/dashboard/conversations/$conversationId': typeof ProjectsProjectIdDashboardConversationsConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/projects'
    | '/welcome'
    | '/projects/$projectId'
    | '/projects/create'
    | '/projects/'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/'
    | '/projects/$projectId/conversations/$conversationId'
    | '/projects/$projectId/dashboard/conversations/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/welcome'
    | '/projects/create'
    | '/projects'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId'
    | '/projects/$projectId/conversations/$conversationId'
    | '/projects/$projectId/dashboard/conversations/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/projects'
    | '/welcome'
    | '/projects/$projectId'
    | '/projects/create'
    | '/projects/'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/'
    | '/projects/$projectId/conversations/$conversationId'
    | '/projects/$projectId/dashboard/conversations/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/dashboard': {
      id: '/projects/$projectId/dashboard'
      path: '/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof ProjectsProjectIdDashboardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/conversations/$conversationId': {
      id: '/projects/$projectId/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/projects/$projectId/conversations/$conversationId'
      preLoaderRoute: typeof ProjectsProjectIdConversationsConversationIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/dashboard/conversations/$conversationId': {
      id: '/projects/$projectId/dashboard/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/projects/$projectId/dashboard/conversations/$conversationId'
      preLoaderRoute: typeof ProjectsProjectIdDashboardConversationsConversationIdRouteImport
      parentRoute: typeof ProjectsProjectIdDashboardRoute
    }
  }
}

interface ProjectsProjectIdDashboardRouteChildren {
  ProjectsProjectIdDashboardConversationsConversationIdRoute: typeof ProjectsProjectIdDashboardConversationsConversationIdRoute
}

const ProjectsProjectIdDashboardRouteChildren: ProjectsProjectIdDashboardRouteChildren =
  {
    ProjectsProjectIdDashboardConversationsConversationIdRoute:
      ProjectsProjectIdDashboardConversationsConversationIdRoute,
  }

const ProjectsProjectIdDashboardRouteWithChildren =
  ProjectsProjectIdDashboardRoute._addFileChildren(
    ProjectsProjectIdDashboardRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdDashboardRoute: typeof ProjectsProjectIdDashboardRouteWithChildren
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdConversationsConversationIdRoute: typeof ProjectsProjectIdConversationsConversationIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdDashboardRoute: ProjectsProjectIdDashboardRouteWithChildren,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdConversationsConversationIdRoute:
    ProjectsProjectIdConversationsConversationIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
